import fs from "fs";
import path from "path";
import { parseSpec } from "./parser.js";
import { Specification } from "./types.js";

// Helper to convert spec ID or name to PascalCase
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

// Helper to generate TS type from field definition type
function mapFieldToTsType(def: any): string {
  switch (def.type) {
    case "string":
    case "ulid":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const itemType =
        def.itemsType === "number"
          ? "number"
          : def.itemsType === "boolean"
            ? "boolean"
            : "any";
      return `${itemType}[]`;
    }
    case "object":
      return "Record<string, any>";
    default:
      return "any";
  }
}

export function runCli(args: string[]) {
  const command = args[0];
  if (command !== "validate" && command !== "compile") {
    console.error("Usage: spec <command> [options]");
    console.error("Commands:");
    console.error("  validate <path>                 Validate specification file(s)");
    console.error("  compile <path> --out <dir>      Compile specification file(s) to TypeScript and JSON");
    process.exit(1);
  }

  const targetPath = args[1];
  if (!targetPath) {
    console.error("Error: Please provide a file or folder path.");
    process.exit(1);
  }

  const absoluteTargetPath = path.resolve(targetPath);
  if (!fs.existsSync(absoluteTargetPath)) {
    console.error(`Error: Path does not exist: ${absoluteTargetPath}`);
    process.exit(1);
  }

  const filesToProcess: string[] = [];
  const stat = fs.statSync(absoluteTargetPath);
  if (stat.isDirectory()) {
    const listFiles = (dir: string) => {
      const entries = fs.readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const res = path.resolve(dir, entry.name);
        if (entry.isDirectory()) {
          listFiles(res);
        } else if (
          entry.name.endsWith(".specify.md") ||
          entry.name.endsWith(".specify.yaml") ||
          entry.name.endsWith(".specify") ||
          (entry.name.endsWith(".md") && entry.name.includes(".specify"))
        ) {
          filesToProcess.push(res);
        }
      }
    };
    listFiles(absoluteTargetPath);
  } else {
    filesToProcess.push(absoluteTargetPath);
  }

  if (filesToProcess.length === 0) {
    console.log("No specification files found to process.");
    return;
  }

  console.log(`Processing ${filesToProcess.length} specification file(s)...`);

  let errorCount = 0;

  for (const file of filesToProcess) {
    try {
      const content = fs.readFileSync(file, "utf-8");
      const spec = parseSpec(content);

      if (command === "validate") {
        console.log(`✅ Validated: ${path.basename(file)} (ID: ${spec.meta.id}, Version: ${spec.meta.version})`);
      } else if (command === "compile") {
        const outIndex = args.indexOf("--out");
        let outDir = outIndex !== -1 ? args[outIndex + 1] : undefined;
        if (!outDir) {
          const oIndex = args.indexOf("-o");
          outDir = oIndex !== -1 ? args[oIndex + 1] : undefined;
        }

        if (!outDir) {
          console.error("Error: --out <dir> or -o <dir> parameter is required for compilation.");
          process.exit(1);
        }

        const absoluteOutDir = path.resolve(outDir);
        if (!fs.existsSync(absoluteOutDir)) {
          fs.mkdirSync(absoluteOutDir, { recursive: true });
        }

        const specName = spec.meta.id.replace("SPECIFICATION:", "").toLowerCase();
        const pascalName = toPascalCase(specName);

        let tsContent = `// Automatically generated by Spec-Kit compiler. DO NOT EDIT.\n`;
        tsContent += `import { Specification } from "../types.js";\n\n`;
        tsContent += `export const SPECIFICATION_${specName.toUpperCase().replace(/-/g, "_")}: Specification = ${JSON.stringify(spec, null, 2)};\n\n`;

        if (spec.schema && spec.schema.fields) {
          tsContent += `export interface ${pascalName}Payload {\n`;
          for (const [fieldName, fieldDef] of Object.entries(spec.schema.fields)) {
            const optionalStr = (fieldDef as any).required ? "" : "?";
            const tsType = mapFieldToTsType(fieldDef);
            tsContent += `  ${fieldName}${optionalStr}: ${tsType};\n`;
          }
          tsContent += `}\n\n`;

          tsContent += `export function validate${pascalName}Payload(payload: any): string[] {\n`;
          tsContent += `  const errors: string[] = [];\n`;
          tsContent += `  if (!payload || typeof payload !== "object") {\n`;
          tsContent += `    return ["Payload must be an object."];\n`;
          tsContent += `  }\n`;

          for (const [fieldName, fieldDef] of Object.entries(spec.schema.fields)) {
            const fd = fieldDef as any;
            if (fd.required) {
              tsContent += `  if (payload.${fieldName} === undefined || payload.${fieldName} === null) {\n`;
              tsContent += `    errors.push('Field "${fieldName}" is required.');\n`;
              tsContent += `  }\n`;
            }
            tsContent += `  if (payload.${fieldName} !== undefined && payload.${fieldName} !== null) {\n`;
            if (fd.type === "array") {
              tsContent += `    if (!Array.isArray(payload.${fieldName})) {\n`;
              tsContent += `      errors.push('Field "${fieldName}" must be an array.');\n`;
              tsContent += `    }\n`;
            } else if (fd.type === "ulid" || fd.type === "string") {
              tsContent += `    if (typeof payload.${fieldName} !== "string") {\n`;
              tsContent += `      errors.push('Field "${fieldName}" must be a string.');\n`;
              tsContent += `    }\n`;
            } else {
              tsContent += `    if (typeof payload.${fieldName} !== "${fd.type}") {\n`;
              tsContent += `      errors.push('Field "${fieldName}" must be of type ${fd.type}.');\n`;
              tsContent += `    }\n`;
            }
            tsContent += `  }\n`;
          }
          tsContent += `  return errors;\n`;
          tsContent += `}\n`;
        }

        const outTsFile = path.join(absoluteOutDir, `${specName}.ts`);
        const outJsonFile = path.join(absoluteOutDir, `${specName}.json`);

        fs.writeFileSync(outTsFile, tsContent);
        fs.writeFileSync(outJsonFile, JSON.stringify(spec, null, 2));

        console.log(`⚡ Compiled: ${path.basename(file)} -> ${path.relative(process.cwd(), outTsFile)} & ${path.relative(process.cwd(), outJsonFile)}`);
      }
    } catch (err: any) {
      console.error(`❌ Error in ${path.basename(file)}: ${err.message}`);
      errorCount++;
    }
  }

  if (errorCount > 0) {
    process.exit(1);
  }
}

// Check if file is run directly
const isDirectRun =
  process.argv[1] &&
  (process.argv[1].endsWith("cli.js") ||
    process.argv[1].endsWith("cli.ts") ||
    process.argv[1].endsWith("cli.mjs"));

if (isDirectRun) {
  runCli(process.argv.slice(2));
}
