// Automatically generated by Spec-Kit compiler. DO NOT EDIT.
import { Specification } from "../types.js";

export const SPECIFICATION_PURCHASE_ORDER: Specification = {
  "meta": {
    "id": "SPECIFICATION:PURCHASE_ORDER",
    "type": "SPECIFICATION",
    "name": "Purchase Order",
    "version": "1.0.0",
    "description": "Especificação de validação, segurança e estados para ordens de compra na plataforma."
  },
  "schema": {
    "fields": {
      "id": {
        "type": "ulid",
        "required": true
      },
      "buyer_id": {
        "type": "ulid",
        "required": true
      },
      "seller_id": {
        "type": "ulid",
        "required": true
      },
      "total_amount": {
        "type": "number",
        "required": true
      },
      "status": {
        "type": "string",
        "required": true
      }
    }
  },
  "security": {
    "roles": [
      "buyer",
      "seller",
      "validator"
    ],
    "requiredCapabilities": [
      "purchase-order:create",
      "purchase-order:approve",
      "purchase-order:reject"
    ]
  },
  "validation": {
    "mode": "single_validator"
  },
  "stateMachine": {
    "initial": "draft",
    "states": {
      "draft": {
        "on": {
          "SUBMIT": "submitted"
        }
      },
      "submitted": {
        "on": {
          "APPROVE": "approved",
          "REJECT": "rejected"
        }
      },
      "approved": {
        "on": {
          "COMPLETE": "completed"
        }
      },
      "rejected": {},
      "completed": {}
    }
  },
  "ui_hints": {
    "super_card": {
      "header": {
        "title_field": "id",
        "subtitle_field": "status"
      },
      "body": {
        "primary_fields": [
          "buyer_id",
          "seller_id",
          "total_amount"
        ]
      }
    }
  }
};

export interface PurchaseOrderPayload {
  id: string;
  buyer_id: string;
  seller_id: string;
  total_amount: number;
  status: string;
}

export function validatePurchaseOrderPayload(payload: any): string[] {
  const errors: string[] = [];
  if (!payload || typeof payload !== "object") {
    return ["Payload must be an object."];
  }
  if (payload.id === undefined || payload.id === null) {
    errors.push('Field "id" is required.');
  }
  if (payload.id !== undefined && payload.id !== null) {
    if (typeof payload.id !== "string") {
      errors.push('Field "id" must be a string.');
    }
  }
  if (payload.buyer_id === undefined || payload.buyer_id === null) {
    errors.push('Field "buyer_id" is required.');
  }
  if (payload.buyer_id !== undefined && payload.buyer_id !== null) {
    if (typeof payload.buyer_id !== "string") {
      errors.push('Field "buyer_id" must be a string.');
    }
  }
  if (payload.seller_id === undefined || payload.seller_id === null) {
    errors.push('Field "seller_id" is required.');
  }
  if (payload.seller_id !== undefined && payload.seller_id !== null) {
    if (typeof payload.seller_id !== "string") {
      errors.push('Field "seller_id" must be a string.');
    }
  }
  if (payload.total_amount === undefined || payload.total_amount === null) {
    errors.push('Field "total_amount" is required.');
  }
  if (payload.total_amount !== undefined && payload.total_amount !== null) {
    if (typeof payload.total_amount !== "number") {
      errors.push('Field "total_amount" must be of type number.');
    }
  }
  if (payload.status === undefined || payload.status === null) {
    errors.push('Field "status" is required.');
  }
  if (payload.status !== undefined && payload.status !== null) {
    if (typeof payload.status !== "string") {
      errors.push('Field "status" must be a string.');
    }
  }
  return errors;
}
